### ISSUE TITLE
Modal pops up twice

### ISSUE THREAD

**Issue by erochest** [erochest/chunk-corpus#5]

**Comment by csbailey5t** [comment]
This seems to be a result of 'done' being passed as a parameter here: https://github.com/scholarslab/chunk-corpus/blob/master/app/scripts/main.js#L216

With 'done' included, the map on L217 runs twice, causing the modal to open twice. In the second run, 'v' is an empty array. This is also the source of the overlay remaining after the modal technically closes, mentioned in #6. There, the overlay for the second trigger of the modal remains open.

Removing done from L216 seems to fix the issue, but I'm working to determine whether it breaks the app otherwise.

**Comment by csbailey5t** [comment]
Fixed in 8720a3948e377aa3e45f71a87a53848351988a16
